include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    use_setters_to_change_properties: ignore
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
