name: mplan_mobile
description: App zum Anzeigen des Messdienerplans der Messdiener St. Vitus Visbek.
publish_to: "none"
version: 1.7.0+18

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  dio: ^5.3.3
  intl: ^0.18.1
  timeago: ^3.5.0
  flutter_localizations:
    sdk: flutter
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1
  collection: ^1.17.2
  flutter_native_splash: ^2.3.3
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  add_2_calendar:
    git:
      url: https://github.com/ja2375/add_2_calendar
      ref: 24eb76acb4acf8a989c309b47caa459ed66197fe
  url_launcher: ^6.2.1
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
  flutter_gen_runner: ^5.3.2
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.5
  riverpod_lint: ^2.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
