name: mplan_mobile
description: App zum Anzeigen des Messdienerplans der Messdiener St. Vitus Visbek.
publish_to: "none"
version: 1.12.0+25

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.1.0
  dio: ^5.3.3
  intl: ^0.20.2
  timeago: ^3.5.0
  flutter_localizations:
    sdk: flutter
  dio_cache_interceptor: ^4.0.5
  http_cache_hive_store: ^5.0.0
  collection: ^1.17.2
  flutter_native_splash: ^2.3.3
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  add_2_calendar_new: 1.0.4
  url_launcher: ^6.2.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.0
  flutter_animate: ^4.3.0
  flutter_widget_from_html_core: ^0.17.0
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.1.0
  awesome_extensions: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^3.2.0
  json_serializable: ^6.7.1
  very_good_analysis: ^9.0.0
  flutter_gen_runner: ^5.3.2
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
